defaults: &defaults
  working_directory: ~/cross-service-messenger
  docker:
    - image: cimg/ruby:2.6.6

version: 2.1
jobs:
  rubocop_test:
    <<: *defaults
    steps:
      - checkout
      - run: bundle --path vendor/bundle
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec_tests:
    <<: *defaults
    steps:
      - checkout
      - run: bundle --path vendor/bundle
      - run:
          name: RSpec
          command: bundle exec rake

      - store_artifacts:
          path: coverage

workflows:
  build:
    jobs:
      - rubocop_test
      - rspec_tests
